<a href="https://colab.research.google.com/github/sangramshitole07/AMLAssignment/blob/main/AMLAssignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

## Pandas Assignment - Solutions

### Question 1: Create a Pandas Series containing the marks: 78, 85, 92, 67, 88. Display its complete Series, values, index, data type, mean, maximum, and minimum.

In [2]:
# 1. Create a Pandas Series
marks_series = pd.Series([78, 85, 92, 67, 88])

print("Complete Series:")
display(marks_series)

print("\nValues:")
display(marks_series.values)

print("\nIndex:")
display(marks_series.index)

print("\nData type:")
display(marks_series.dtype)

print("\nMean:")
display(marks_series.mean())

print("\nMaximum:")
display(marks_series.max())

print("\nMinimum:")
display(marks_series.min())

Complete Series:

0    78
1    85
2    92
3    67
4    88
dtype: int64

Values:

array([78, 85, 92, 67, 88])

Index:

RangeIndex(start=0, stop=5, step=1)

Data type:

dtype('int64')

Mean:

np.float64(82.0)

Maximum:

92

Minimum:

67

### Question 2: Create a Series containing student marks (Asha: 85, Ravi: 78, Meena: 92, Kiran: 74, Arun: 88). Display the marks of Meena.

In [3]:
# 2. Create a Series with student names and marks
student_marks = pd.Series({
    'Asha': 85,
    'Ravi': 78,
    'Meena': 92,
    'Kiran': 74,
    'Arun': 88
})

print("Complete Series:")
display(student_marks)

print("\nMarks of Meena:")
display(student_marks['Meena'])

Complete Series:

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64

Marks of Meena:

np.int64(92)

### Question 3: Create a DataFrame with Name, Age, Department, and Marks. Display the complete DataFrame, first 3 rows, last 2 rows, shape, column names, and data types.

In [4]:
# 3. Create the DataFrame
data = {
    'Name': ['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'],
    'Age': [22, 23, 21, 24, 22],
    'Department': ['CSE', 'ECE', 'CSE', 'ME', 'ECE'],
    'Marks': [85, 78, 92, 74, 88]
}
df = pd.DataFrame(data)

print("Complete DataFrame:")
display(df)

print("\nFirst 3 rows:")
display(df.head(3))

print("\nLast 2 rows:")
display(df.tail(2))

print("\nShape:")
display(df.shape)

print("\nColumn names:")
display(df.columns)

print("\nData types:")
display(df.dtypes)

Complete DataFrame:

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows:

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:

    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

Shape:

(5, 4)

Column names:

Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')

Data types:

Name          object
Age            int64
Department    object
Marks          int64
dtype: object

### Question 4: Using the previous DataFrame, display `info()`, `describe()`, number of rows, and number of columns.

In [5]:
# 4. Display DataFrame information and statistics

print("DataFrame Info:")
display(df.info())

print("\nDataFrame Description (numerical columns):")
display(df.describe())

print("\nNumber of rows:")
display(df.shape[0])

print("\nNumber of columns:")
display(df.shape[1])

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

None

DataFrame Description (numerical columns):

             Age      Marks
count   5.000000   5.000000
mean   22.400000  83.400000
std     1.140175   7.334848
min    21.000000  74.000000
25%    22.000000  78.000000
50%    22.000000  85.000000
75%    23.000000  88.000000
max    24.000000  92.000000

Number of rows:

5

Number of columns:

4

### Question 5: Using the DataFrame `df`, display the 'Name' column, 'Marks' column, and 'Name' and 'Marks' columns together.

In [6]:
# 5. Display specific columns

print("Name column:")
display(df['Name'])

print("\nMarks column:")
display(df['Marks'])

print("\nName and Marks columns together:")
display(df[['Name', 'Marks']])

Name column:

0     Asha
1     Ravi
2    Meena
3    Kiran
4     Arun
Name: Name, dtype: object

Marks column:

0    85
1    78
2    92
3    74
4    88
Name: Marks, dtype: int64

Name and Marks columns together:

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

### Question 6: Display the first row using `iloc`, third row using `iloc`, rows 1 to 3, and 'Name' and 'Marks' columns using `loc`.

In [7]:
# 6. Accessing rows and columns using iloc and loc

print("First row using iloc:")
display(df.iloc[0])

print("\nThird row using iloc:")
display(df.iloc[2])

print("\nRows 1 to 3 (index 1 and 2) using iloc:")
display(df.iloc[1:3])

print("\nName and Marks columns using loc:")
display(df.loc[:, ['Name', 'Marks']])

First row using iloc:

Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

Third row using iloc:

Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

Rows 1 to 3 (index 1 and 2) using iloc:

    Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Name and Marks columns using loc:

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

### Question 7: Find students scoring above 80, students scoring between 75 and 90, students belonging to CSE, and CSE students scoring above 80.

In [8]:
# 7. Filtering the DataFrame

print("Students scoring above 80:")
display(df[df['Marks'] > 80])

print("\nStudents scoring between 75 and 90:")
display(df[(df['Marks'] >= 75) & (df['Marks'] <= 90)])

print("\nStudents belonging to CSE:")
display(df[df['Department'] == 'CSE'])

print("\nCSE students scoring above 80:")
display(df[(df['Department'] == 'CSE') & (df['Marks'] > 80)])

Students scoring above 80:

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

Students scoring between 75 and 90:

   Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

Students belonging to CSE:

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

CSE students scoring above 80:

    Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

### Question 8: Display students belonging to either CSE or ECE.

In [9]:
# 8. Display students belonging to either CSE or ECE

print("Students belonging to either CSE or ECE:")
display(df[(df['Department'] == 'CSE') | (df['Department'] == 'ECE')])
# Alternatively, using isin()
# display(df[df['Department'].isin(['CSE', 'ECE'])])

Students belonging to either CSE or ECE:

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88

### Question 9: Add a new column called 'Result'. Students scoring 75 or above should receive "Pass", otherwise "Fail".

In [10]:
# 9. Add a new column 'Result'
df['Result'] = np.where(df['Marks'] >= 75, 'Pass', 'Fail')

print("DataFrame with 'Result' column:")
display(df)

DataFrame with 'Result' column:

    Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

### Question 10: Assign grades according to the given criteria: ≥ 90 (A), ≥ 80 (B), ≥ 70 (C), < 70 (D).

In [11]:
# 10. Assign grades based on Marks
def assign_grade(marks):
    if marks >= 90:
        return 'A'
    elif marks >= 80:
        return 'B'
    elif marks >= 70:
        return 'C'
    else:
        return 'D'

df['Grade'] = df['Marks'].apply(assign_grade)

print("DataFrame with 'Grade' column:")
display(df)

DataFrame with 'Grade' column:

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

### Question 11: Sort students by marks in ascending order, by marks in descending order, and by Department and then Marks.

In [12]:
# 11. Sort students

print("Students sorted by marks in ascending order:")
display(df.sort_values(by='Marks', ascending=True))

print("\nStudents sorted by marks in descending order:")
display(df.sort_values(by='Marks', ascending=False))

print("\nStudents sorted by Department and then Marks:")
display(df.sort_values(by=['Department', 'Marks']))

Students sorted by marks in ascending order:

    Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

Students sorted by marks in descending order:

    Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

Students sorted by Department and then Marks:

    Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

### Question 12: Consider the given DataFrame `students` with missing values. Find missing values, the number of missing values in each column, and rows containing missing values.

In [13]:
# 12. Handling missing values
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}
students = pd.DataFrame(data)

print("Original DataFrame with missing values:")
display(students)

print("\nMissing values (boolean DataFrame):")
display(students.isnull())

print("\nNumber of missing values in each column:")
display(students.isnull().sum())

print("\nRows containing missing values:")
display(students[students.isnull().any(axis=1)])

Original DataFrame with missing values:

    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

Missing values (boolean DataFrame):

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

Number of missing values in each column:

Name     0
Age      1
Marks    1
dtype: int64

Rows containing missing values:

    Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

### Question 13: Replace missing 'Age' with the average Age and missing 'Marks' with the average Marks in the `students` DataFrame.

In [14]:
# 13. Replace missing values with averages

# Calculate average age and marks
avg_age = students['Age'].mean()
avg_marks = students['Marks'].mean()

# Fill missing values
students['Age'].fillna(avg_age, inplace=True)
students['Marks'].fillna(avg_marks, inplace=True)

print("DataFrame after replacing missing values with averages:")
display(students)

DataFrame after replacing missing values with averages:

/tmp/ipykernel_2549/4029726825.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Age'].fillna(avg_age, inplace=True)
/tmp/ipykernel_2549/4029726825.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Marks'].fillna(avg_marks, inplace=True)

    Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

### Question 14: Remove rows containing missing values from the original `students_original` DataFrame (before filling). This requires recreating `students` for demonstration.

In [15]:
# Recreate the original students DataFrame with NaNs for this question
data_original = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}
students_original = pd.DataFrame(data_original)

print("Original DataFrame for removal of missing values:")
display(students_original)

# 14. Remove rows containing missing values
students_cleaned = students_original.dropna()

print("\nDataFrame after removing rows with missing values:")
display(students_cleaned)

Original DataFrame for removal of missing values:

    Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

DataFrame after removing rows with missing values:

    Name   Age  Marks
0   Asha  22.0   85.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

### Question 15: Consider the given `df2` DataFrame with duplicate names. Find duplicates, display duplicate rows, and remove duplicates.

In [16]:
# 15. Handling duplicate values
data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}
df2 = pd.DataFrame(data)

print("Original DataFrame with duplicates:")
display(df2)

print("\nBoolean Series indicating duplicate rows:")
display(df2.duplicated())

print("\nDuplicate rows:")
display(df2[df2.duplicated()])

# Remove duplicates (keeps the first occurrence by default)
df2_unique = df2.drop_duplicates()

print("\nDataFrame after removing duplicates:")
display(df2_unique)

Original DataFrame with duplicates:

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

Boolean Series indicating duplicate rows:

0    False
1    False
2    False
3     True
4    False
dtype: bool

Duplicate rows:

   Name  Marks
3  Asha     85

DataFrame after removing duplicates:

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

### Question 16: Given a DataFrame `marks`, calculate the Mean, Median, Maximum, Minimum, Standard deviation, and Sum of the 'Marks' column.

In [17]:
# 16. Calculate descriptive statistics
marks_df = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

print("Original Marks DataFrame:")
display(marks_df)

print("\nMean of Marks:")
display(marks_df['Marks'].mean())

print("\nMedian of Marks:")
display(marks_df['Marks'].median())

print("\nMaximum of Marks:")
display(marks_df['Marks'].max())

print("\nMinimum of Marks:")
display(marks_df['Marks'].min())

print("\nStandard deviation of Marks:")
display(marks_df['Marks'].std())

print("\nSum of Marks:")
display(marks_df['Marks'].sum())

Original Marks DataFrame:

  Student  Marks
0       A     78
1       B     85
2       C     92
3       D     67
4       E     88

Mean of Marks:

np.float64(82.0)

Median of Marks:

85.0

Maximum of Marks:

92

Minimum of Marks:

67

Standard deviation of Marks:

9.82344135219425

Sum of Marks:

np.int64(410)

### Question 17: Consider the given DataFrame `df`. Find the average marks by department, maximum marks by department, number of students in each department, and for each department, calculate Mean, Minimum, Maximum, and Count.

In [18]:
# 17. Grouping and aggregation
data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun", "Divya"],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE", "CSE"],
    "Marks": [85, 78, 92, 74, 88, 80]
}
df_group = pd.DataFrame(data)

print("Original DataFrame:")
display(df_group)

print("\nAverage marks by department:")
display(df_group.groupby('Department')['Marks'].mean())

print("\nMaximum marks by department:")
display(df_group.groupby('Department')['Marks'].max())

print("\nNumber of students in each department:")
display(df_group.groupby('Department').size())

print("\nFor each department, Mean, Minimum, Maximum, Count:")
display(df_group.groupby('Department')['Marks'].agg(['mean', 'min', 'max', 'count']))

Original DataFrame:

    Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

Average marks by department:

Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

Maximum marks by department:

Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

Number of students in each department:

Department
CSE    3
ECE    2
ME     1
dtype: int64

For each department, Mean, Minimum, Maximum, Count:

                 mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

### Question 18: Create two DataFrames, `students_df` and `marks_df`, and combine them using `StudentID`.

In [19]:
# 18. Combining DataFrames (Merge)
students_df = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks_df = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

print("Students DataFrame:")
display(students_df)

print("\nMarks DataFrame:")
display(marks_df)

combined_df = pd.merge(students_df, marks_df, on='StudentID')

print("\nCombined DataFrame:")
display(combined_df)

Students DataFrame:

   StudentID   Name
0        101   Asha
1        102   Ravi
2        103  Meena
3        104  Kiran

Marks DataFrame:

   StudentID  Marks
0        101     85
1        102     78
2        103     92
3        104     74

Combined DataFrame:

   StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

### Question 19: Use the provided dataset to perform various analyses: display first five records, find dimensions, average final mark, highest/lowest scoring student, students scoring above 80, average marks by department, students with attendance above 80%, sort by FinalMarks, add 'Result' column, add 'Performance' category, and find the department with the highest average FinalMarks.

In [20]:
# 19. Comprehensive Data Analysis
data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df_analysis = pd.DataFrame(data)

print("Original DataFrame:")
display(df_analysis)

print("\nFirst five records:")
display(df_analysis.head(5))

print("\nDimensions of the dataset (rows, columns):")
display(df_analysis.shape)

print("\nAverage final mark:")
display(df_analysis['FinalMarks'].mean())

highest_scorer = df_analysis.loc[df_analysis['FinalMarks'].idxmax()]
print("\nHighest-scoring student:")
display(highest_scorer)

lowest_scorer = df_analysis.loc[df_analysis['FinalMarks'].idxmin()]
print("\nLowest-scoring student:")
display(lowest_scorer)

print("\nStudents scoring above 80:")
display(df_analysis[df_analysis['FinalMarks'] > 80])

print("\nAverage marks by department:")
display(df_analysis.groupby('Department')['FinalMarks'].mean())

print("\nStudents having attendance above 80%:")
display(df_analysis[df_analysis['Attendance'] > 80])

print("\nStudents sorted by FinalMarks:")
display(df_analysis.sort_values(by='FinalMarks', ascending=False))

# Add 'Result' column
df_analysis['Result'] = np.where(df_analysis['FinalMarks'] >= 70, 'Pass', 'Fail')
print("\nDataFrame with 'Result' column:")
display(df_analysis)

# Add 'Performance' category
def assign_performance_category(marks):
    if marks >= 90:
        return 'Excellent'
    elif marks >= 80:
        return 'Very Good'
    elif marks >= 70:
        return 'Good'
    else:
        return 'Needs Improvement'

df_analysis['Performance'] = df_analysis['FinalMarks'].apply(assign_performance_category)
print("\nDataFrame with 'Performance' category:")
display(df_analysis)

# Find the department having the highest average FinalMarks
avg_final_marks_by_dept = df_analysis.groupby('Department')['FinalMarks'].mean()
highest_avg_dept = avg_final_marks_by_dept.idxmax()
print(f"\nDepartment with the highest average FinalMarks: {highest_avg_dept}")
display(avg_final_marks_by_dept)

Original DataFrame:

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

First five records:

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

Dimensions of the dataset (rows, columns):

(8, 5)

Average final mark:

np.float64(81.625)

Highest-scoring student:

Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

Lowest-scoring student:

Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

Students scoring above 80:

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Average marks by department:

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

Students having attendance above 80%:

    Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Students sorted by FinalMarks:

    Name Department  Attendance  Internal  FinalMarks
2  Meena        CSE          96        94          96
7  Priya        ECE          95        91          93
5  Divya        CSE          88        86          89
0   Asha        CSE          92        85          88
4   Arun        ECE          82        80          83
1   Ravi        ECE          75        72          74
6   John         ME          72        70          68
3  Kiran         ME          68        65          62

DataFrame with 'Result' column:

    Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

DataFrame with 'Performance' category:

,Name,Department,Attendance,Internal,FinalMarks,Result,Performance
0,Asha,CSE,92,85,88,Pass,Very Good
1,Ravi,ECE,75,72,74,Pass,Good
2,Meena,CSE,96,94,96,Pass,Excellent
3,Kiran,ME,68,65,62,Fail,Needs Improvement
4,Arun,ECE,82,80,83,Pass,Very Good
5,Divya,CSE,88,86,89,Pass,Very Good
6,John,ME,72,70,68,Fail,Needs Improvement
7,Priya,ECE,95,91,93,Pass,Excellent

Department with the highest average FinalMarks: CSE

Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

### Question 20: Create an `employees` DataFrame and determine various metrics: average, max/min salary, employee with highest salary, employees earning above ₹60,000, average salary/experience by department, number of employees per department, sort by salary, find IT employees with >3 years experience, and add a 'SalaryLevel' column.

In [21]:
# 20. Employee Data Analysis
employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

print("Original Employees DataFrame:")
display(employees)

print("\nAverage salary:")
display(employees['Salary'].mean())

print("\nMaximum salary:")
display(employees['Salary'].max())

print("\nMinimum salary:")
display(employees['Salary'].min())

highest_paid_employee = employees.loc[employees['Salary'].idxmax()]
print("\nEmployee receiving the highest salary:")
display(highest_paid_employee)

print("\nEmployees earning above ₹60,000:")
display(employees[employees['Salary'] > 60000])

print("\nAverage salary for each department:")
display(employees.groupby('Department')['Salary'].mean())

print("\nAverage experience by department:")
display(employees.groupby('Department')['Experience'].mean())

print("\nNumber of employees in each department:")
display(employees.groupby('Department').size())

print("\nEmployees sorted by salary:")
display(employees.sort_values(by='Salary', ascending=False))

print("\nIT employees with more than 3 years of experience:")
display(employees[(employees['Department'] == 'IT') & (employees['Experience'] > 3)])

# Add 'SalaryLevel' column
def assign_salary_level(salary):
    if salary >= 75000:
        return 'High'
    elif 50000 <= salary < 75000:
        return 'Medium'
    else:
        return 'Low'

employees['SalaryLevel'] = employees['Salary'].apply(assign_salary_level)
print("\nDataFrame with 'SalaryLevel' column:")
display(employees)

Original Employees DataFrame:

  Employee Department  Experience  Salary
0      E01         IT           5   60000
1      E02         HR           3   45000
2      E03         IT           7   75000
3      E04    Finance           4   65000
4      E05         HR           6   55000
5      E06    Finance           8   85000
6      E07         IT           2   48000
7      E08    Finance           5   70000

Average salary:

np.float64(62875.0)

Maximum salary:

85000

Minimum salary:

45000

Employee receiving the highest salary:

Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

Employees earning above ₹60,000:

  Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

Average salary for each department:

Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

Average experience by department:

Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

Number of employees in each department:

Department
Finance    3
HR         2
IT         3
dtype: int64

Employees sorted by salary:

  Employee Department  Experience  Salary
5      E06    Finance           8   85000
2      E03         IT           7   75000
7      E08    Finance           5   70000
3      E04    Finance           4   65000
0      E01         IT           5   60000
4      E05         HR           6   55000
6      E07         IT           2   48000
1      E02         HR           3   45000

IT employees with more than 3 years of experience:

  Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

DataFrame with 'SalaryLevel' column:

  Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium